
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/themavine' #change it according to your repository name



# Profile information
yourname: Jongjin Kim  ## put your name
title: 'Jongjin Kim &amp; Hompage'  ## your title
location: HKUST, Kowloon, Hong Kong SAR


## Social Profiles
facebook: http://www.facebook.com/jongjin.kim.372  ## your facebook account url



# Update all the sections by editing the files inside _includes folder.
